<?php
declare(strict_types=1);
require_once __DIR__.'/../config/database.php';
require_once __DIR__.'/../models/EngagementLetter.php';
require_once __DIR__.'/../models/AuditLog.php';
require_once __DIR__.'/../includes/role_check.php';
require_once __DIR__.'/invoice_controller.php';

const LETTER_LIST_URL='/MNS_CORPORATE/frontend/views/engagement_letters/list.php';
function handleEngagementLetterRequest(): void {startSecureSession();requireAuth();$a=$_GET['action']??'list';if($a==='store')storeLetter();elseif($a==='update')updateLetter((int)($_POST['id']??0));elseif($a==='send')sendLetter((int)($_POST['id']??0));elseif($a==='sign')signLetter((int)($_POST['id']??0));elseif($a==='create')showLetterCreate();elseif($a==='edit')showLetterEdit((int)($_GET['id']??0));elseif($a==='show')showLetter((int)($_GET['id']??0));elseif($a==='sign_form')showLetterSign((int)($_GET['id']??0));else listLetters();}
function listLetters(): void {$pdo=getDatabaseConnection();$m=new EngagementLetter($pdo);$filters=letterFilters();$u=currentUser();if($u['role']==='CLIENT'){$c=clientForUser($pdo,(int)$u['id']);$filters['visible_client_id']=$c['id']??0;}elseif($u['role']!=='EXPERT')redirect('/MNS_CORPORATE/index.php');$page=max(1,(int)($_GET['page']??1));$perPage=20;$letters=$m->findAll($filters,$perPage,($page-1)*$perPage);$total=$m->countAll($filters);$clients=fetchInvoiceClients($pdo);$missions=fetchInvoiceMissions($pdo);renderLetterView('list.php',compact('letters','total','filters','page','perPage','clients','missions'));}
function showLetterCreate(): void {requireRole(['EXPERT']);$letter=null;$pdo=getDatabaseConnection();$clients=fetchInvoiceClients($pdo);$missions=fetchInvoiceMissions($pdo);renderLetterView('create.php',compact('letter','clients','missions'));}
function showLetterEdit(int $id): void {requireRole(['EXPERT']);$letter=findLetterOrRedirect($id);if($letter['status']==='SIGNEE'){redirect(LETTER_LIST_URL);} $content=letterContent($letter);$pdo=getDatabaseConnection();$clients=fetchInvoiceClients($pdo);$missions=fetchInvoiceMissions($pdo);renderLetterView('edit.php',compact('letter','content','clients','missions'));}
function showLetter(int $id): void {$letter=findLetterOrRedirect($id);$m=new EngagementLetter(getDatabaseConnection());if(!$m->canUserAccessLetter(currentUser(),$letter))redirect(LETTER_LIST_URL);$content=letterContent($letter);renderLetterView('show.php',compact('letter','content'));}
function showLetterSign(int $id): void {requireRole(['CLIENT']);$letter=findLetterOrRedirect($id);$m=new EngagementLetter(getDatabaseConnection());if(!$m->canUserAccessLetter(currentUser(),$letter)||$letter['status']!=='ENVOYEE')redirect(LETTER_LIST_URL);renderLetterView('sign.php',compact('letter'));}
function storeLetter(): void {requireRole(['EXPERT']);letterPostOnly();$pdo=getDatabaseConnection();$data=letterInput($_POST)+['created_by'=>currentUserId()];$errors=validateLetter($pdo,$data);if($errors){setFlashMessage('error',implode(' ',$errors));showLetterCreate();return;}$data['file_path']=saveLetterContent($data['content']);$id=(new EngagementLetter($pdo))->create($data);letterAudit($pdo,'CREATION_LETTRE_MISSION','Lettre #'.$id);redirect(LETTER_LIST_URL);}
function updateLetter(int $id): void {requireRole(['EXPERT']);letterPostOnly();$letter=findLetterOrRedirect($id);if($letter['status']==='SIGNEE')redirect(LETTER_LIST_URL);$pdo=getDatabaseConnection();$data=letterInput($_POST);$errors=validateLetter($pdo,$data);if($errors){setFlashMessage('error',implode(' ',$errors));showLetterEdit($id);return;}$data['file_path']=saveLetterContent($data['content'],$letter['file_path']);$data['status']='BROUILLON';(new EngagementLetter($pdo))->update($id,$data);letterAudit($pdo,'MODIFICATION_LETTRE_MISSION','Lettre #'.$id);redirect(LETTER_LIST_URL);}
function sendLetter(int $id): void {requireRole(['EXPERT']);letterPostOnly();$pdo=getDatabaseConnection();$letter=findLetterOrRedirect($id);if($letter['status']!=='BROUILLON')redirect(LETTER_LIST_URL);(new EngagementLetter($pdo))->markAsSent($id);notifyLetterClient($pdo,$letter,'Lettre de mission envoyee','Une lettre de mission vous attend.');letterAudit($pdo,'ENVOI_LETTRE_MISSION','Lettre #'.$id);redirect(LETTER_LIST_URL);}
function signLetter(int $id): void {requireRole(['CLIENT']);letterPostOnly();$pdo=getDatabaseConnection();$letter=findLetterOrRedirect($id);$m=new EngagementLetter($pdo);if(!$m->canUserAccessLetter(currentUser(),$letter)||$letter['status']!=='ENVOYEE'||empty($_POST['confirm']))redirect(LETTER_LIST_URL);$name=trim((string)($_POST['signed_by_name']??''));$text=trim((string)($_POST['signature_text']??''));if($name===''||$text===''){setFlashMessage('error','Signature incomplete.');redirect('/MNS_CORPORATE/frontend/views/engagement_letters/sign.php?id='.$id);} $m->sign($id,$name,$text);notifyExpertsLetter($pdo,$id);letterAudit($pdo,'SIGNATURE_LETTRE_MISSION','Lettre #'.$id);redirect('/MNS_CORPORATE/frontend/views/engagement_letters/show.php?id='.$id);}
function letterInput(array $in): array {foreach(['client_id','mission_id','title','content'] as $k)$d[$k]=trim((string)($in[$k]??''));return $d;}
function validateLetter(PDO $pdo,array $d): array {$e=[];if((int)$d['client_id']<=0)$e[]='Client obligatoire.';if($d['mission_id']!==''&&!missionBelongsToClient($pdo,(int)$d['mission_id'],(int)$d['client_id']))$e[]='Mission invalide.';if($d['title']==='')$e[]='Titre obligatoire.';if($d['content']==='')$e[]='Texte obligatoire.';return $e;}
function saveLetterContent(string $content, ?string $existing=null): string {$dir=__DIR__.'/../../frontend/assets/uploads/engagement_letters';if(!is_dir($dir))mkdir($dir,0755,true);$name=$existing?basename($existing):(bin2hex(random_bytes(12)).'.txt');$path=$dir.DIRECTORY_SEPARATOR.$name;file_put_contents($path,$content);return 'frontend/assets/uploads/engagement_letters/'.$name;}
function letterContent(array $letter): string {$p=$letter['file_path']?__DIR__.'/../../'.$letter['file_path']:'';return $p&&is_file($p)?(string)file_get_contents($p):'';}
function notifyLetterClient(PDO $pdo,array $letter,string $title,string $msg): void {$s=$pdo->prepare('SELECT user_id FROM clients WHERE id=:id');$s->execute(['id'=>$letter['client_id']]);$r=$s->fetch(PDO::FETCH_ASSOC);if($r&&$r['user_id'])createInternalNotification($pdo,(int)$r['user_id'],$title,$msg,'ENGAGEMENT_LETTER',(int)$letter['id'],true);}
function notifyExpertsLetter(PDO $pdo,int $id): void {$s=$pdo->prepare("SELECT id FROM users WHERE role='EXPERT'");$s->execute();foreach($s->fetchAll(PDO::FETCH_ASSOC) as $u)createInternalNotification($pdo,(int)$u['id'],'Lettre signee','Une lettre de mission a ete signee.','ENGAGEMENT_LETTER',$id,true);}
function letterFilters(): array {$f=[];foreach(['q','client_id','mission_id','status'] as $k){$v=trim((string)($_GET[$k]??''));if($v!=='')$f[$k]=$v;}return $f;}
function findLetterOrRedirect(int $id): array {$l=(new EngagementLetter(getDatabaseConnection()))->findById($id);if(!$l)redirect(LETTER_LIST_URL);return $l;}
function letterPostOnly(): void {if(!isPostRequest())redirect(LETTER_LIST_URL);}
function letterAudit(PDO $pdo,string $a,string $d): void {(new AuditLog($pdo))->log(['user_id'=>currentUserId(),'action'=>$a,'description'=>$d,'ip_address'=>$_SERVER['REMOTE_ADDR']??null]);}
function renderLetterView(string $view,array $vars=[]): void {extract($vars,EXTR_SKIP);if(!defined('MNS_CONTROLLER_RENDER'))define('MNS_CONTROLLER_RENDER',true);require __DIR__.'/../../frontend/views/engagement_letters/'.$view;}
