<?php
declare(strict_types=1);

require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/accounting_rules.php';
require_once __DIR__ . '/../includes/accounting_helpers.php';
require_once __DIR__ . '/../includes/role_check.php';
require_once __DIR__ . '/../models/Invoice.php';
require_once __DIR__ . '/../models/Payment.php';
require_once __DIR__ . '/../models/AuditLog.php';
require_once __DIR__ . '/notification_controller.php';

const INVOICE_LIST_URL = '/MNS_CORPORATE/frontend/views/invoices/list.php';

function handleInvoiceRequest(): void { startSecureSession(); requireAuth(); $a=$_GET['action']??'list'; if($a==='store')storeInvoice(); elseif($a==='update')updateInvoice((int)($_POST['id']??0)); elseif($a==='status')changeInvoiceStatus((int)($_POST['id']??0)); elseif($a==='create')showInvoiceCreate(); elseif($a==='edit')showInvoiceEdit((int)($_GET['id']??0)); elseif($a==='show')showInvoice((int)($_GET['id']??0)); else listInvoices(); }

function listInvoices(): void { $pdo=getDatabaseConnection(); $m=new Invoice($pdo); $overdueCount=$m->markOverdue(); if($overdueCount>0){invoiceAudit($pdo,'MISE_EN_RETARD_FACTURE',$overdueCount.' facture(s) mise(s) en retard automatiquement.');} $filters=invoiceFilters(); $user=currentUser(); if($user['role']==='CLIENT'){ $c=clientForUser($pdo,(int)$user['id']); $filters['visible_client_id']=$c['id']??0; } elseif($user['role']!=='EXPERT'){ redirect('/MNS_CORPORATE/index.php'); } $page=max(1,(int)($_GET['page']??1)); $perPage=20; $invoices=$m->findAll($filters,$perPage,($page-1)*$perPage); $total=$m->countAll($filters); $clients=fetchInvoiceClients($pdo); $missions=fetchInvoiceMissions($pdo); renderInvoiceView('list.php',compact('invoices','total','filters','page','perPage','clients','missions')); }
function showInvoiceCreate(): void { requireRole(['EXPERT']); $invoice=null; $pdo=getDatabaseConnection(); $clients=fetchInvoiceClients($pdo); $missions=fetchInvoiceMissions($pdo); renderInvoiceView('create.php',compact('invoice','clients','missions')); }
function showInvoiceEdit(int $id): void { requireRole(['EXPERT']); $invoice=findInvoiceOrRedirect($id); $pdo=getDatabaseConnection(); $clients=fetchInvoiceClients($pdo); $missions=fetchInvoiceMissions($pdo); renderInvoiceView('edit.php',compact('invoice','clients','missions')); }
function showInvoice(int $id): void { $invoice=findInvoiceOrRedirect($id); if(!invoiceCanAccess(currentUser(),$invoice)){redirect(INVOICE_LIST_URL);} $payments=(new Payment(getDatabaseConnection()))->findByInvoice($id); $paid=(new Invoice(getDatabaseConnection()))->getPaymentsTotal($id); $balance=max(0,(float)$invoice['total_amount']-$paid); renderInvoiceView('show.php',compact('invoice','payments','paid','balance')); }

function storeInvoice(): void { requireRole(['EXPERT']); invoicePostOnly(); $pdo=getDatabaseConnection(); $data=invoiceInput($_POST)+['created_by'=>currentUserId()]; $errors=validateInvoiceData($pdo,$data); if($errors){$_SESSION['old_input']=$data; setFlashMessage('error',implode(' ',$errors)); showInvoiceCreate(); return;} $id=(new Invoice($pdo))->create($data); invoiceAudit($pdo,'CREATION_FACTURE','Facture #'.$id); if($data['status']==='ENVOYEE'){ notifyInvoiceClient($pdo,$id,'Facture envoyee','Une facture vous a ete envoyee.'); invoiceAudit($pdo,'ENVOI_FACTURE','Facture envoyee #'.$id);} redirect(INVOICE_LIST_URL); }
function updateInvoice(int $id): void { requireRole(['EXPERT']); invoicePostOnly(); $pdo=getDatabaseConnection(); $model=new Invoice($pdo); $invoice=findInvoiceOrRedirect($id); if($invoice['status']==='ANNULEE'){setFlashMessage('error','Facture annulee non modifiable.'); redirect(INVOICE_LIST_URL);} $data=invoiceInput($_POST); $errors=validateInvoiceData($pdo,$data,$id); if($model->getPaymentsTotal($id)>(float)$data['total_amount']){$errors[]='Total inferieur au montant deja paye.';} if($errors){$_SESSION['old_input']=$data; setFlashMessage('error',implode(' ',$errors)); showInvoiceEdit($id); return;} $model->update($id,$data); $model->refreshPaymentStatus($id); invoiceAudit($pdo,'MODIFICATION_FACTURE','Facture #'.$id); redirect(INVOICE_LIST_URL); }
function changeInvoiceStatus(int $id): void { requireRole(['EXPERT']); invoicePostOnly(); $pdo=getDatabaseConnection(); $model=new Invoice($pdo); $invoice=findInvoiceOrRedirect($id); $new=$_POST['status']??''; $allowed=($invoice['status']==='BROUILLON'&&$new==='ENVOYEE')||($invoice['status']==='ENVOYEE'&&in_array($new,['ANNULEE','EN_RETARD'],true)); if(!$allowed||($new==='ANNULEE'&&$invoice['status']==='PAYEE')){setFlashMessage('error','Changement de statut interdit.'); redirect(INVOICE_LIST_URL);} $stmt=$pdo->prepare('UPDATE invoices SET status = :status WHERE id = :id'); $stmt->execute(['status'=>$new,'id'=>$id]); if($new==='ENVOYEE'){notifyInvoiceClient($pdo,$id,'Facture envoyee','Une facture vous a ete envoyee.'); invoiceAudit($pdo,'ENVOI_FACTURE','Facture #'.$id);} if($new==='ANNULEE')invoiceAudit($pdo,'ANNULATION_FACTURE','Facture #'.$id); if($new==='EN_RETARD')invoiceAudit($pdo,'MISE_EN_RETARD_FACTURE','Facture #'.$id); redirect(INVOICE_LIST_URL); }

function invoiceInput(array $in): array { $subtotal=(float)($in['subtotal']??0); $rate=(float)(($in['tax_rate']??'')===''?TVA_STANDARD_RATE:$in['tax_rate']); return ['client_id'=>trim((string)($in['client_id']??'')),'mission_id'=>trim((string)($in['mission_id']??'')),'invoice_number'=>trim((string)($in['invoice_number']??'')),'issue_date'=>trim((string)($in['issue_date']??'')),'due_date'=>trim((string)($in['due_date']??'')),'subtotal'=>$subtotal,'tax_rate'=>$rate,'tax_amount'=>calculateVat($subtotal,$rate),'total_amount'=>calculateAmountTtc($subtotal,$rate),'status'=>trim((string)($in['status']??'BROUILLON')),'notes'=>trim((string)($in['notes']??''))]; }
function validateInvoiceData(PDO $pdo,array $d,int $id=0): array { $e=[]; $m=new Invoice($pdo); if((int)$d['client_id']<=0)$e[]='Client obligatoire.'; if($d['mission_id']!==''&&!missionBelongsToClient($pdo,(int)$d['mission_id'],(int)$d['client_id']))$e[]='Mission invalide pour ce client.'; if($d['invoice_number']===''||$m->invoiceNumberExists($d['invoice_number'],$id))$e[]='Numero facture obligatoire et unique.'; if($d['issue_date']===''||$d['due_date']===''||$d['due_date']<$d['issue_date'])$e[]='Dates invalides.'; if((float)$d['subtotal']<=0)$e[]='Montant HT obligatoire.'; if(!in_array($d['status'],['BROUILLON','ENVOYEE'],true)&&$id===0)$e[]='Statut initial invalide.'; return $e; }
function invoiceFilters(): array { $f=[]; foreach(['q','client_id','mission_id','status','issue_from','issue_to','due_from','due_to'] as $k){$v=trim((string)($_GET[$k]??'')); if($v!=='')$f[$k]=$v;} return $f; }
function fetchInvoiceClients(PDO $pdo): array {$s=$pdo->prepare('SELECT id, company_name FROM clients ORDER BY company_name');$s->execute();return $s->fetchAll(PDO::FETCH_ASSOC);}
function fetchInvoiceMissions(PDO $pdo): array {$s=$pdo->prepare('SELECT id,title,client_id FROM missions ORDER BY title');$s->execute();return $s->fetchAll(PDO::FETCH_ASSOC);}
function missionBelongsToClient(PDO $pdo,int $missionId,int $clientId): bool {$s=$pdo->prepare('SELECT id FROM missions WHERE id=:m AND client_id=:c');$s->execute(['m'=>$missionId,'c'=>$clientId]);return $s->fetch()!==false;}
function clientForUser(PDO $pdo,int $uid): ?array {$s=$pdo->prepare('SELECT id FROM clients WHERE user_id=:id');$s->execute(['id'=>$uid]);$r=$s->fetch(PDO::FETCH_ASSOC);return $r?:null;}
function invoiceCanAccess(array $user,array $invoice): bool { if($user['role']==='EXPERT')return true; if($user['role']==='CLIENT'){ $c=clientForUser(getDatabaseConnection(),(int)$user['id']); return $c&&(int)$c['id']===(int)$invoice['client_id']; } return false; }
function findInvoiceOrRedirect(int $id): array {$i=(new Invoice(getDatabaseConnection()))->findById($id); if(!$i){redirect(INVOICE_LIST_URL);} return $i;}
function notifyInvoiceClient(PDO $pdo,int $invoiceId,string $title,string $msg): void {$i=(new Invoice($pdo))->findById($invoiceId); if($i){$c=$pdo->prepare('SELECT user_id FROM clients WHERE id=:id');$c->execute(['id'=>$i['client_id']]);$r=$c->fetch(PDO::FETCH_ASSOC); if($r&&$r['user_id']) createInternalNotification($pdo,(int)$r['user_id'],$title,$msg,'INVOICE',$invoiceId,true);}}
function invoicePostOnly(): void { if(!isPostRequest()) redirect(INVOICE_LIST_URL); }
function invoiceAudit(PDO $pdo,string $a,string $d): void {(new AuditLog($pdo))->log(['user_id'=>currentUserId(),'action'=>$a,'description'=>$d,'ip_address'=>$_SERVER['REMOTE_ADDR']??null]);}
function renderInvoiceView(string $view,array $vars=[]): void {extract($vars,EXTR_SKIP); if(!defined('MNS_CONTROLLER_RENDER'))define('MNS_CONTROLLER_RENDER',true); require __DIR__.'/../../frontend/views/invoices/'.$view;}
