<?php
declare(strict_types=1);
if (!defined('MNS_CONTROLLER_RENDER')) { require_once __DIR__ . '/../../../backend/controllers/mission_controller.php'; handleMissionCatalogRequest(); return; }
require_once __DIR__ . '/../../../backend/includes/helpers.php'; require_once __DIR__ . '/../../../backend/includes/role_check.php'; requireRole(['EXPERT']);
$flash = getFlashMessage(); $pages = max(1, (int) ceil(($total ?? 0) / ($perPage ?? 20))); $queryBase = $filters ?? []; require_once __DIR__ . '/../includes/header.php';
?>
<div class="d-flex"><?php require_once __DIR__ . '/../includes/sidebar.php'; ?><main class="container-fluid py-4">
<?php if ($flash !== null): ?><div class="alert alert-<?php echo e($flash['type'] === 'success' ? 'success' : 'danger'); ?>"><?php echo e($flash['message']); ?></div><?php endif; ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h4 mb-1">Catalogue des missions</h1><div class="text-muted"><?php echo e((string) ($total ?? 0)); ?> resultat(s)</div></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="/MNS_CORPORATE/frontend/views/missions/list.php">Missions</a><a class="btn btn-primary" href="/MNS_CORPORATE/frontend/views/missions/catalog_create.php">Nouveau type</a></div></div>
<form class="row g-2 mb-3" method="get" action="/MNS_CORPORATE/frontend/views/missions/catalog_list.php"><div class="col-md-5"><input class="form-control" type="search" name="q" value="<?php echo e($filters['q'] ?? ''); ?>" placeholder="Nom du type de mission"></div><div class="col-md-3"><select class="form-select" name="is_active"><option value="">Tous</option><option value="1" <?php echo (($filters['is_active'] ?? '') === '1') ? 'selected' : ''; ?>>Actifs</option><option value="0" <?php echo (($filters['is_active'] ?? '') === '0') ? 'selected' : ''; ?>>Inactifs</option></select></div><div class="col-md-4"><button class="btn btn-outline-secondary">Filtrer</button><a class="btn btn-link" href="/MNS_CORPORATE/frontend/views/missions/catalog_list.php">Reinitialiser</a></div></form>
<div class="table-responsive bg-white border rounded"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Nom</th><th>Description</th><th>Duree defaut</th><th>Statut</th><th>Creation</th><th class="text-end">Actions</th></tr></thead><tbody>
<?php foreach (($catalogItems ?? []) as $item): ?><tr><td><?php echo e($item['name']); ?></td><td><?php echo e($item['description']); ?></td><td><?php echo e((string) $item['default_duration_days']); ?></td><td><span class="badge text-bg-<?php echo (int) $item['is_active'] === 1 ? 'success' : 'secondary'; ?>"><?php echo (int) $item['is_active'] === 1 ? 'Actif' : 'Inactif'; ?></span></td><td><?php echo e($item['created_at']); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="/MNS_CORPORATE/frontend/views/missions/catalog_edit.php?id=<?php echo e((string) $item['id']); ?>">Modifier</a><form method="post" action="/MNS_CORPORATE/frontend/views/missions/catalog_list.php?action=toggle" class="d-inline" onsubmit="return confirm('Confirmer cette action ?');"><input type="hidden" name="id" value="<?php echo e((string) $item['id']); ?>"><button class="btn btn-sm btn-outline-danger" type="submit"><?php echo (int) $item['is_active'] === 1 ? 'Desactiver' : 'Activer'; ?></button></form></td></tr><?php endforeach; ?>
<?php if (($catalogItems ?? []) === []): ?><tr><td colspan="6" class="text-center text-muted py-4">Aucun type de mission trouve.</td></tr><?php endif; ?>
</tbody></table></div><nav class="mt-3"><ul class="pagination"><?php for ($i = 1; $i <= $pages; $i++): ?><?php $queryBase['page'] = $i; ?><li class="page-item <?php echo $i === ($page ?? 1) ? 'active' : ''; ?>"><a class="page-link" href="/MNS_CORPORATE/frontend/views/missions/catalog_list.php?<?php echo e(http_build_query($queryBase)); ?>"><?php echo e((string) $i); ?></a></li><?php endfor; ?></ul></nav>
</main></div><?php require_once __DIR__ . '/../includes/footer.php'; ?>
