<?php
declare(strict_types=1);
if (!defined('MNS_CONTROLLER_RENDER')) { require_once __DIR__ . '/../../../backend/controllers/deadline_controller.php'; handleDeadlineRequest(); return; }
require_once __DIR__ . '/../../../backend/includes/helpers.php'; require_once __DIR__ . '/../../../backend/includes/role_check.php'; $user=currentUser(); $isExpert=($user['role']??'')==='EXPERT'; $flash=getFlashMessage(); $pages=max(1,(int)ceil(($total??0)/($perPage??20))); $queryBase=$filters??[]; unset($queryBase['assigned_user_id'],$queryBase['visible_client_id']); require_once __DIR__ . '/../includes/header.php';
?>
<div class="d-flex"><?php require_once __DIR__ . '/../includes/sidebar.php'; ?><main class="container-fluid py-4">
<?php if($flash): ?><div class="alert alert-<?php echo e($flash['type']==='success'?'success':'danger'); ?>"><?php echo e($flash['message']); ?></div><?php endif; ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h4 mb-1">Echeances fiscales</h1><div class="text-muted"><?php echo e((string)($total??0)); ?> resultat(s)</div></div><div class="d-flex gap-2"><?php if(($user['role']??'')==='EXPERT'): ?><a class="btn btn-primary" href="/MNS_CORPORATE/frontend/views/deadlines/create.php">Nouvelle echeance</a><form method="post" action="/MNS_CORPORATE/frontend/views/deadlines/list.php?action=generate" class="d-flex gap-2"><input class="form-control" name="year" value="<?php echo e(date('Y')); ?>" style="width:90px"><button class="btn btn-outline-secondary">Generer TVA/IS</button></form><?php endif; ?><a class="btn btn-outline-dark" href="/MNS_CORPORATE/frontend/views/deadlines/calendar.php">Calendrier</a></div></div>
<form method="get" class="row g-2 mb-3"><div class="col-md-3"><input class="form-control" name="q" value="<?php echo e($filters['q']??''); ?>" placeholder="Titre ou description"></div><?php if($isExpert): ?><div class="col-md-2"><select class="form-select" name="client_id"><option value="">Tous clients</option><?php foreach(($clients??[]) as $c): ?><option value="<?php echo e((string)$c['id']); ?>" <?php echo (($filters['client_id']??'')==$c['id'])?'selected':''; ?>><?php echo e($c['company_name']); ?></option><?php endforeach; ?></select></div><?php endif; ?><div class="col-md-2"><select class="form-select" name="status"><option value="">Tous statuts</option><?php foreach(FiscalDeadline::STATUSES as $s): ?><option value="<?php echo e($s); ?>" <?php echo (($filters['status']??'')===$s)?'selected':''; ?>><?php echo e($s); ?></option><?php endforeach; ?></select></div><div class="col-md-2"><input class="form-control" type="date" name="date_from" value="<?php echo e($filters['date_from']??''); ?>"></div><div class="col-md-2"><input class="form-control" type="date" name="date_to" value="<?php echo e($filters['date_to']??''); ?>"></div><div class="col-md-1"><button class="btn btn-outline-secondary w-100">Filtrer</button></div></form>
<div class="table-responsive bg-white border rounded"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Titre</th><th>Client</th><th>Mission</th><th>Date</th><th>Statut</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach(($deadlines??[]) as $d): ?><tr class="<?php echo $d['status']==='EN_RETARD'?'table-danger':''; ?>"><td><?php echo e($d['title']); ?></td><td><?php echo e($d['company_name']); ?></td><td><?php echo e($d['mission_title']); ?></td><td><?php echo e($d['deadline_date']); ?></td><td><span class="badge text-bg-<?php echo $d['status']==='TERMINEE'?'success':($d['status']==='EN_RETARD'?'danger':'warning'); ?>"><?php echo e($d['status']); ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="/MNS_CORPORATE/frontend/views/deadlines/show.php?id=<?php echo e((string)$d['id']); ?>">Voir</a><?php if(($user['role']??'')==='EXPERT'): ?> <a class="btn btn-sm btn-outline-secondary" href="/MNS_CORPORATE/frontend/views/deadlines/edit.php?id=<?php echo e((string)$d['id']); ?>">Modifier</a><?php if($d['status']!=='TERMINEE'): ?><form class="d-inline" method="post" action="/MNS_CORPORATE/frontend/views/deadlines/list.php?action=complete"><input type="hidden" name="id" value="<?php echo e((string)$d['id']); ?>"><button class="btn btn-sm btn-outline-success">Terminer</button></form><?php endif; ?><?php endif; ?></td></tr><?php endforeach; ?><?php if(($deadlines??[])===[]): ?><tr><td colspan="6" class="text-center text-muted py-4">Aucune echeance.</td></tr><?php endif; ?></tbody></table></div>
<nav class="mt-3"><ul class="pagination"><?php for($i=1;$i<=$pages;$i++): $queryBase['page']=$i; ?><li class="page-item <?php echo $i===($page??1)?'active':''; ?>"><a class="page-link" href="?<?php echo e(http_build_query($queryBase)); ?>"><?php echo e((string)$i); ?></a></li><?php endfor; ?></ul></nav>
</main></div><?php require_once __DIR__ . '/../includes/footer.php'; ?>
